### ISSUE TITLE
Per-project encryption

### ISSUE THREAD

**Issue by LoganDark** [allotropelabs/nitrogen#2]
Currently, project contents are stored server-side, but in plain text. This is not good practice. I'm planning on implementing AES encryption.

**Comment by LoganDark** [comment]
It will be client-side encryption, the server will only be able to see the encrypted data. Published projects will not be encrypted for obvious reasons, since the server needs to send the contents to the client and decryption would require the account password.

**Comment by tetraoxygen** [comment]
# Allotrope's stance on privacy

Allotrope is firmly committed to preserving your privacy. This includes on products like Nitrogen, where we will encrypt anything that is not published. Once you publish a site, the unencrypted version is uploaded to the server running Nitrogen. We alert the user as to this behavior. 

For more information, go to our [Privacy Policy](https://allotropelabs.com/legal/privacy).

**Comment by LoganDark** [comment]
Relax 😛
