### ISSUE TITLE
Password tester and generator do not work

### ISSUE THREAD

**Issue by LoganDark** [allotropelabs/nitrogen#4]
Throws an error in console due to the methods not existing

**Comment by tetraoxygen** [comment]
`notImplementedError`

**Comment by LoganDark** [comment]
```py
Traceback (most recent call last):
  File "<Nitrogen>", line 1, in <module>
NotImplementedError
```

Let's keep the issue comments to things actually related to the issue 😛

**Comment by LoganDark** [comment]
Removing these unimplemented functionalities for now.
