### ISSUE TITLE
Add Allotrope Accounts support

### ISSUE THREAD

**Issue by tetraoxygen** [allotropelabs/nitrogen#6]
We are currently relying on an - admittedly _really_ secure - account system written by Logan. We need to add support for Allotrope Accounts, which are powered by Firebase Auth.

**Comment by LoganDark** [comment]
This would require a ton of extra effort for a feature that would add nothing to the user experience. What advantages would adding Allotrope Accounts support have?

**Comment by tetraoxygen** [comment]
It would mean that users would have one account that would work EVERYWHERE, including on future products. It also has full support for 2FA, magic sign in links, Google Accounts, and mobile platforms.

**Comment by LoganDark** [comment]
1. 2FA is easy to implement on its own if it's required,
2. Magic sign in links are also fairly easy to implement,
3. Google Accounts would be a bit harder to implement, but we don't need Firebase for that,
4. Nitrogen already works on mobile, except for a couple layout issues (#7)

Moving to Firebase would also require migrating the entire _very real_ userbase over manually, as well as providing information _we don't have_ (such as email addresses)

**Comment by tetraoxygen** [comment]
Future products. The bits of Graphene (Future textbook streaming app) that I've implemented already have support for Allotrope Accounts. All you have to do for a sign in flow is use the one I've already built that has all of this implemented, and have accounts be checked by the Firebase library, of which there's one for both the Web and Node.

**Comment by tetraoxygen** [comment]
Also, while all of them are possible to implement otherwise, Firebase is overall less work. One library to deal with. Plus, as you told me in an iMessage, you were having a hard time getting NodeMailer to work with your SMTP server.

**Comment by LoganDark** [comment]
Cool. Graphene can use Allotrope Accounts.

While it will be easy _in the future_ to kick off new products with the Accounts sign in / register flow, Nitrogen's account management flow has already been completed. There are already existing accounts in the system that do not contain enough information to migrate to Firebase.

The Nitrogen flow is simple - username, password. No headache. No email required. I'd like to keep it that way. Password resets _are_ a concern you've raised in the past, and with no email address as a backup communication method, they would require manual approval. However, aside from that one problem, the current account system works just fine.

I'm closing the issue for now. If at some point it becomes _necessary_ to upgrade, we can reopen it, but for now I'm choosing to keep things the way they are, for the sake of not having to spend time recreating something that's already done well currently.

**Comment by LoganDark** [comment]
This is being worked on in the `accounts` branch

**Comment by tetraoxygen** [comment]
Allotrope Accounts no longer uses Firebase, and uses our own custom system. Userdata will be end-to-end encrypted where possible.

**Comment by Colean128** [comment]
allotrope accounts are now dead. case closed

**Comment by tetraoxygen** [comment]
Nitrogen is dead as a service, so it's never getting Allotrope Accounts.
